### ISSUE TITLE
Вызов функции от идентификатора считается присваиванием

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-parser#1]
![image](https://app.gitkraken.com/api/glo/boards/5c286465fef389000fe21eaf/attachments/5c287ee7fef389000fe221f6)

**Comment by asosnoviy** [comment]
Почини картинку плз

**Comment by nixel2007** [comment]
Куда-то удалились с гиткракена :( там проблема в том, что А(); считается как assignment->doCall. Хотя никакого assignment тут нет

**Comment by asosnoviy** [comment]
И только теперь я понял о чем был этот ишуз)
