### ISSUE TITLE
Синхронизация develop и master

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-parser#131]
В репе разъехались master и develop ветки. Мастер новее девелопа на 40 коммитов. 
Если мы используем девелоп, надо сделать его основным бранчем, синхронизировать обе ветки и пульнуть релиз 0.20.0.

@theshadowco прошу помощи

**Comment by theshadowco** [comment]
@nixel2007 прав изменить настройки ветки нет, ветки синхронизировал

**Comment by nixel2007** [comment]
прав довыдал, ветку поменял. спасибо!
