### ISSUE TITLE
[FP] Срабатывает проверка MissingReturnedValueDescription на функцию большим сложным описанием

### ISSUE THREAD

**Issue by vbondarevsky** [1c-syntax/bsl-parser#141]
## Диагностика
MissingReturnedValueDescription

## Описание ложного срабатывания диагностики
Срабатывает проверка "Добавьте описание возвращаемого значения функции" на функцию, в которой есть описание возвращаемого значение, но оно достаточно объемное и сложное

## Пример кода
https://sonar.openbsl.ru/project/issues?id=connector&issues=AXvE-BGKlPnNfWNZM9iU&open=AXvE-BGKlPnNfWNZM9iU

## Скриншоты
![image](https://user-images.githubusercontent.com/11818792/132915974-a436c28b-9e8b-4d79-ae15-4debcadecbe5.png)

**Comment by theshadowco** [comment]
После обновления зависимостей поправится
