### ISSUE TITLE
Ошибка при разборе инструкции #Область

### ISSUE THREAD

**Issue by lChagelishvili** [1c-syntax/bsl-parser#17]
Такой код 
```bsl
#Область Область
#КонецОбласти
```
приводит к ошибке разбора

```
Analyzing files... 100% [===========================] 1/1 (0:00:00 / 0:00:00) line 2:9 no viable alternative at input '#ОбластьОбласть'
```

**Comment by asosnoviy** [comment]
@nixel2007 А у нас проблема с любой `#Область Кейворд` =(

**Comment by nixel2007** [comment]
может быть правила в лексере подвинуть выше определения кейвордов? по идее
это должно повысить приоритет у лексера.

пн, 18 февр. 2019 г. в 18:04, Alexey Sosnoviy <notifications@github.com>:

**Comment by asosnoviy** [comment]
А они в моде с препроцессором =(
