### ISSUE TITLE
[BUG] Некорректный разбор запросов к внешним источникам данных

### ISSUE THREAD

**Issue by ovcharenko-di** [1c-syntax/bsl-parser#218]
Запросы к ВИД не разбираются в ветке develop.
В 0.19 разбирались.

Пример:

```bsl
ВЫБРАТЬ
Таблица1.Поле1 КАК Поле1
ИЗ
ВнешнийИсточникДанных.ВнешнийИсточникДанных1.Таблица.Таблица1 КАК Таблица1
```

Ошибка:
![image](https://user-images.githubusercontent.com/24920942/205322748-f9a22904-9221-4f9f-b2a6-33ba4825d183.png)

**Comment by theshadowco** [comment]
in develop
