### ISSUE TITLE
Не поддерживается функция языка запросов УНИКАЛЬНЫЙИДЕНТИФИКАТОР

### ISSUE THREAD

**Issue by potoyalo** [1c-syntax/bsl-parser#264]
Либо комбинация функций `ПРЕДСТАВЛЕНИЕ(УНИКАЛЬНЫЙИДЕНТИФИКАТОР(...))`

![изображение](https://github.com/1c-syntax/bsl-parser/assets/1996464/84582a83-fd69-40d3-b15b-ecc19aa3071c)

Обсуждение: https://t.me/bsl_language_server/111673

**Comment by theshadowco** [comment]
В текущей версии (0.22.1) - работает. надо смотреть версию плагина, которым пользуетесь
