### ISSUE TITLE
Разбить tryStatement  на tryBlockStatement  и cathBlockStatement

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-parser#32]
Что бы можно было подписаться на разные секции.
Вроде же ничего не сломается?

**Comment by nixel2007** [comment]
Я бы оставил tryStatement, потому что это именно неделимый стэйтмент. А вот внутри него уже можно выделить именные блоки.

**Comment by asosnoviy** [comment]
Ну да, это явно не стейтменты. Ща накидаю.

**Comment by nixel2007** [comment]
У нас давно релиза не было. Может тэгнимся?

**Comment by asosnoviy** [comment]
а мы как то на коммиты сползли... Давай вместе с релизом всего.
