### ISSUE TITLE
Поддержка быстрого использования результата Новый из OneScript

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-parser#45]
В OneScript можно написать следующий код и он будет успешно работать:

```bsl
Версия = (Новый СистемнаяИнформация).ВерсияСреды
```

В текущей грамматике работа опретатора Новый не может быть использована как результат для дальнейшей обработки в expression

**Comment by EvilBeaver** [comment]
Как сделать assign to me?

**Comment by nixel2007** [comment]
Емнип, эти права есть только у коллабораторов. Повесить на тебя?

**Comment by nixel2007** [comment]
Вообще вроде как это уже есть...

https://github.com/1c-syntax/bsl-parser/blob/master/src/main/antlr/BSLParser.g4#L239

Возможно оно работает не совсем корректно.
