### ISSUE TITLE
Уменьшение размера jar-файла

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-parser#47]
copy https://github.com/1c-syntax/bsl-language-server/issues/556
>Сейчас внутри жарника есть много лишней требухи (открыть как зип архив и удивиться). JUnit, c# рантайм ANTLR и прочее.Надо пройтись по зависимостям и сделать exlude лишнего.

**Comment by nixel2007** [comment]
Да, парсер вообще ничего с собой не пакует. Кажется, антлр зависимость протекла в бсл лс

**Comment by nixel2007** [comment]
Осталось понять, плохо ли это :)
