### ISSUE TITLE
Не символы

### ISSUE THREAD

**Issue by MinimaJack** [1c-syntax/bsl-parser#62]
Не являются символами
```
  PREPROC_INSERT_SYMBOL
  PREPROC_ENDINSERT_SYMBOL
  PREPROC_DELETE_SYMBOL
  PREPROC_ENDDELETE_SYMBOL
```

**Comment by asosnoviy** [comment]
@nixel2007 А ихуз про что? про то что их когда то забыли? или про то что они есть, но должны быть не символами?

**Comment by MinimaJack** [comment]
@asosnoviy должны быть не символами

**Comment by theshadowco** [comment]
@MinimaJack @nixel2007 
Таска еще актуальна?

**Comment by nixel2007** [comment]
Думаю, актуальна. Правильно будет токены оставить, но назвать их не _SYMBOL, а как-то иначе. Есть же у нас PREPROC_IF, не символ. Вот и тут тоже что-то такое должно быть. Может быть просто _SYMBOL отрезать и пускай живёт.

**Comment by theshadowco** [comment]
Так они давно называются иначе

![image](https://user-images.githubusercontent.com/9591731/156881853-a560f1d7-3147-453a-ba75-e89ec25669a1.png)

**Comment by nixel2007** [comment]
А, значит, можно закрывать
