### ISSUE TITLE
[BUG] Ошибка Парсинга модуля

### ISSUE THREAD

**Issue by DoublesunRUS** [1c-syntax/bsl-parser#67]
**Версия**
> 0.15.2

**Описание ошибки диагностики**
> Ошибка распора исходного кода
{
	"resource": "/Users/kapral/Разработка/rcp-git/ru.capralow.dt.bslls.validator/BSLLanguageServer/src/Catalogs/Диагностики/Forms/ФормаЭлемента/Module.bsl",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "ParseError",
	"severity": 8,
	"message": "Ошибка разбора исходного кода. Ожидался один из следующих токенов: RETURN_KEYWORD, CONTINUE_KEYWORD, GOTO_KEYWORD, BREAK_KEYWORD, EXECUTE_KEYWORD, ADDHANDLER_KEYWORD, REMOVEHANDLER_KEYWORD",
	"source": "bsl-language-server",
	"startLineNumber": 35,
	"startColumn": 1,
	"endLineNumber": 35,
	"endColumn": 2
}

**Пример кода**
```bsl
#Область Переменные

// CodeBlockBecforeSub
&НаКлиенте
Перем CodeBlockBeforeSub;

#КонецОбласти

#Область КвикФиксы

&НаКлиенте
Процедура UsingThisForm(А) Экспорт
	
	А = ЭтаФорма;
	
КонецПроцедуры

#КонецОбласти

#Область ОбработчикиСобытийФормы

&НаСервере
Процедура ПриСозданииНаСервере()

	ДанныеФормыВЗначение(ЭтотОбъект, Тип("СправочникОбъект.Диагностики"));

КонецПроцедуры

#КонецОбласти

#Область СлужебныеПроцедурыИФункции

CodeBlockBeforeSub = Ложь;

&НаКлиенте
Процедура CodeBlockBeforeSub()

	CodeBlockBeforeSub = Истина;

КонецПроцедуры

#КонецОбласти
```

**Comment by nixel2007** [comment]
![image](https://user-images.githubusercontent.com/1132840/87644037-478fad00-c754-11ea-95b8-2b911a0a56ca.png)
![image](https://user-images.githubusercontent.com/1132840/87644073-4f4f5180-c754-11ea-8491-63c6bc2f604f.png)

**Comment by theshadowco** [comment]
ошибки парсера нет... закрываем?

**Comment by nixel2007** [comment]
Почему нет? Мои скрины выше.

**Comment by theshadowco** [comment]
так не правильно жеж переменную писать между методов...

**Comment by nixel2007** [comment]
@theshadowco это же поддержка грамматики тестера. когда объявления методов могут быть и сверху с снизу.

**Comment by theshadowco** [comment]
ептить, я забыл о такой его особенности

**Comment by theshadowco** [comment]
а может его в отдельный вынести? там еще исполнительна подходе, со своими рулеткой и куртизанками

**Comment by nixel2007** [comment]
Он только этим и отличается. Больше ничего не делали

**Comment by artbear** [comment]
Формально в 1С это синтакс-ошибка и задачу нужно закрывать.
а у автора видно, что этот код находится внутри формы 1С, и модуль формы невалидный.

**Comment by nixel2007** [comment]
Тестер все же хорошо бы поддержать.

**Comment by nixel2007** [comment]
Ошибка набора кода. Код между процедурами не поддерживается и поддерживаться не планирует. см. #136
