### ISSUE TITLE
Ошибка в тесте лексера на Поле.Неопределено

### ISSUE THREAD

**Issue by demidych** [1c-syntax/bsl-parser#81]
В тесте лексера вместо проверки правильности разбора строки "Поле.Неопределено" ошибочно проверяется "Поле.Ложь"

Ошибка в строке №317 ([ссылка](https://github.com/1c-syntax/bsl-parser/blob/master/src/test/java/com/github/_1c_syntax/bsl/parser/BSLLexerTest.java#L317))

assertMatch("Поле.ЛОЖЬ", BSLLexer.IDENTIFIER, BSLLexer.DOT, BSLLexer.IDENTIFIER);

**Comment by asosnoviy** [comment]
А почему ошибочно?

**Comment by theshadowco** [comment]
Проверка на ``Поле.Неопределено` строкой ниже (в английской нотации), а соответствие русского и английского кейворда в отдельном тесте

**Comment by demidych** [comment]
Вот весь блок проверки
```
    assertMatch("НеопределенО", BSLLexer.UNDEFINED);
    assertMatch("UNDEFINeD", BSLLexer.UNDEFINED);
    assertMatch("Поле.ЛОЖЬ", BSLLexer.IDENTIFIER, BSLLexer.DOT, BSLLexer.IDENTIFIER);
    assertMatch("Field.UNDEFINED", BSLLexer.IDENTIFIER, BSLLexer.DOT, BSLLexer.IDENTIFIER);
```

По которому видно, что хотели проверить на Поле.Неопределено, но скопировали с блока выше и забыли поменять.

Посмотрите код выше ниже, там однотипные проверки, например вот на Поле.Процедура

```
    assertMatch("ПРОЦЕДУрА", BSLLexer.PROCEDURE_KEYWORD);
    assertMatch("PROCEDUrE", BSLLexer.PROCEDURE_KEYWORD);
    assertMatch("Поле.ПРОЦЕДУРА", BSLLexer.IDENTIFIER, BSLLexer.DOT, BSLLexer.IDENTIFIER);
    assertMatch("Field.PROCEDURE", BSLLexer.IDENTIFIER, BSLLexer.DOT, BSLLexer.IDENTIFIER);
```

**Comment by theshadowco** [comment]
@demidych 
реквест пришлешь?

**Comment by demidych** [comment]
Постараюсь разобраться как это сделать.

**Comment by theshadowco** [comment]
> Постараюсь разобраться как это сделать.

1. поставить идею
2.  форкнуть реп на гитхабе
3. создать ветку
4. склонировать на локальный комп и переключиться на ветку
5. открыть проект в идее
6. в терминале идеи написать gradlew test и дождаться, пока он все скачает, настроит и прогонит тест
7. исправить и повторить 6. 
8. если ошибок нет, фиксировать изменения, отправить в свой реп-форк
9. открыть текущий реп на закладке pull requests и создать реквест из своего репа и своей ветку сюда
10. ждать...

**Comment by demidych** [comment]
@theshadowco 
Сделал 1-9, жду

**Comment by nixel2007** [comment]
Отлично, спасибо!
