### ISSUE TITLE
Вопрос - Как узнать данные виртуальной таблицы 1С? сколько у нее параметров может быть, название\тип 1го параметра и т.п.

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-parser#91]
Для решения https://github.com/1c-syntax/bsl-language-server/pull/1556 будет полезно понимать описания виртуальных таблиц 1С
Например, что вирт.таблицы Остатки 1й параметр Период, а ОстаткиИОбороты 1 и 2й.
что в параметре №2 (3,4 и т.п. для бух. и расчетных регистров) могут быть условия к вирт.таблице

@theshadowco Подскажи, есть ли такая информация? или ее нет ?

**Comment by nixel2007** [comment]
Это точно не в парсер. Метаданные лежат в mdclasses.

**Comment by theshadowco** [comment]
в парсере такого нет, это должно быть в пока не реализованном контексте, который отдаст mdclasses

**Comment by artbear** [comment]
парсер ведь имеет инфу о виртуальных таблицах, поэтому я и подумал, что рядом же хранятся же и более подробные данные.

код посмотрел, нету )

закрываю.
