### ISSUE TITLE
Поддержка аннотаций параметров OS

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-parser#93]
@asosnoviy @EvilBeaver 
Вопросы
 - Аннотации для параметров полностью аналогичны аннотациям методов по структуре и расположению... ?
 - аннотаций для параметра может быть несколько?

**Comment by nixel2007** [comment]
В исходниках оскрипта вроде был подробный тест на это дело. Ещё возможно в исходниках либы reflector

**Comment by EvilBeaver** [comment]
Да, аннотаций параметров может быть несколько, насколько я знаю. Но это неточно

**Comment by nixel2007** [comment]
https://github.com/1c-syntax/1c-syntax/blob/master/spec/fixtures/grammar/syntax_test_bsl.os#L5-L35

**Comment by artbear** [comment]
А чего гадать-то? есть же тест в 1скрипте

**Comment by artbear** [comment]
https://github.com/EvilBeaver/OneScript/blob/develop/tests/annotations.os

**Comment by artbear** [comment]
ну да, Никита этот файл и заюзал.
