### ISSUE TITLE
В тексте запроса не поддерживаются соединения с источником в виде параметра запроса

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-parser#98]
Конфигуратор не выдает ошибок на таких выражениях, а парсер падает.
```sdbl
ВЫБРАТЬ
	Таблица.Ссылка КАК Ссылка,
	Валюты .Ссылка КАК Ссылка1
ПОМЕСТИТЬ ВТ
ИЗ
	&Таблица КАК Таблица
	ЛЕВОЕ СОЕДИНЕНИЕ Справочник.Валюты КАК Валюты 
	ПО Таблица.Ссылка = Валюты .Ссылка
```

- 
![image](https://user-images.githubusercontent.com/2920817/116867209-5f69ec00-ac15-11eb-98f9-c9208b5179ae.png)
- .

- ![image](https://user-images.githubusercontent.com/2920817/116867107-292c6c80-ac15-11eb-9ff3-91ff817e25b4.png)

**Comment by nixel2007** [comment]
Разве в рантайме не будет ошибок? Из тз же возможна только выборка в вт
